import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Image from 'next/image'
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import useNFT from '../hooks/useNFT';
import { Box, Container, Typography, Stack, Button, Grid, Card, CardMedia, CardContent, CardActions } from '@mui/material';

interface nftsData {
  image_original_url?: string;
  image_preview_url?: string;
  image_url?: string;
}

const Home: NextPage = () => {
  const { nfts } = useNFT();
  console.log(nfts);
  const lastItemOriginalUrl = (nfts as nftsData[])[nfts.length - 1]?.image_preview_url || '';

  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />
        <main>
          {/* Hero unit */}
          <Stack
            spacing={2}
            sx={{
              bgcolor: 'background.paper',
              pt: 8,
            }}

          >
            <Box
              sx={{
                // width: '5vw',
                // height: '5vh',
                borderRadius: 2,
              }}
            >
              <Image src={lastItemOriginalUrl} alt="123"
                width={100}
                height={100}
              />
            </Box>
          </Stack>
          <Typography
            component="h1"
            variant="h2"
            align="center"
            color="text.primary"
            gutterBottom
            sx={{ mt: '20px', }}
          >
            Here is your fish :
          </Typography>
          <Container sx={{ py: 2 }} maxWidth="md">
            <Grid container spacing={4}>
              {nfts.map((nft: nftsData) => (
                <Grid item key={nft.image_original_url} xs={12} sm={6} md={4}>
                  <Card
                    sx={{
                      height: '100%', display: 'flex', flexDirection: 'column',
                      borderRadius: '50%',
                    }}
                  >
                    <CardMedia
                      component="div"
                      sx={{
                        // 16:9
                        pt: '100%',
                      }}
                      image={nft.image_preview_url || ''}
                    />
                  </Card>
                </Grid>
              ))}
            </Grid>
          </Container>
        </main>
      </main>
    </div>
  );
};

export default Home;
